# Generated by Django 3.0.3 on 2020-02-10 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Stock', models.IntegerField(blank=True, null=True)),
                ('Supplier_Company', models.CharField(blank=True, max_length=30, null=True)),
                ('Previous_Price', models.FloatField(blank=True, null=True)),
                ('Current_Price', models.FloatField(blank=True, null=True)),
                ('Description', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
