# Generated by Django 3.0.3 on 2020-02-11 02:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocklist',
            name='Current_Price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='stocklist',
            name='Description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='stocklist',
            name='Previous_Price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='stocklist',
            name='Product_Name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stocklist',
            name='Stock',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='stocklist',
            name='Supplier_Company',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Name', models.CharField(max_length=50, null=True)),
                ('Number', models.IntegerField(null=True)),
                ('Supplier_Company', models.CharField(max_length=30, null=True)),
                ('Previous_Price', models.FloatField(null=True)),
                ('Current_Price', models.FloatField(null=True)),
                ('Description', models.CharField(max_length=200, null=True)),
                ('Status', models.CharField(choices=[('Stock', 'Stock'), ('Sell', 'Sell')], max_length=10, null=True)),
                ('Date_Created', models.DateTimeField(auto_now=True, null=True)),
                ('stocklist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.StockList')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
