# Generated by Django 3.0.3 on 2020-02-11 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200211_0853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='Current_Price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Description',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Previous_Price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Product_Name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Supplier_Company',
        ),
    ]
