# Generated by Django 3.0.3 on 2020-02-11 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200211_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocklist',
            name='Stock',
            field=models.IntegerField(default=0),
        ),
    ]
