# Generated by Django 3.0.3 on 2020-02-12 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200211_2249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stocklist',
            old_name='Supplier_Company',
            new_name='Supplier',
        ),
    ]
